name: Build Project

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45 # 设置超时时间
    strategy:
      matrix:
        platform: [android, linux]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-pub-

      - name: Upgrade Dependencies
        run: |
          flutter pub outdated
          flutter pub upgrade --major-versions

      - name: Set up Android SDK
        if: ${{ matrix.platform == 'android' }}
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          rm commandlinetools.zip

      - name: Set up Environment Variables
        if: ${{ matrix.platform == 'android' }}
        run: |
          echo "export ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Install Android SDK Tools
        if: ${{ matrix.platform == 'android' }}
        run: |
          sdkmanager --update
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Install Linux Dependencies
        if: ${{ matrix.platform == 'linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libayatana-appindicator3-dev \
            libkeybinder-3.0-dev \
            libgtk-3-dev \
            cmake \
            ninja-build

      - name: Download Missing Library
        if: ${{ matrix.platform == 'linux' }}
        run: |
          mkdir -p libclash/linux
          curl -L -o libclash/linux/clash https://example.com/path/to/clash-binary
          chmod +x libclash/linux/clash

      - name: Set up Java 17
        if: ${{ matrix.platform == 'android' }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Android
        if: ${{ matrix.platform == 'android' }}
        env:
          JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64
        run: |
          flutter clean
          flutter build apk --release

      - name: Build Linux
        if: ${{ matrix.platform == 'linux' }}
        run: |
          flutter clean
          flutter build linux

      - name: Verify Build Output
        run: |
          if [ "${{ matrix.platform }}" == "android" ]; then
            ls -lah build/app/outputs/flutter-apk/
          elif [ "${{ matrix.platform }}" == "linux" ]; then
            ls -lah build/linux/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-build
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/linux/*
